### ISSUE TITLE
Baud rate wrong?

### ISSUE THREAD

**Issue by Deathlesss** [openenergymonitor/guide#31]
Hello,

Please see the issue mentioned here: https://community.openenergymonitor.org/t/serial-monitor-gibberish/6546

It seems that when I followed the guide to connect the emonTH to Atom/PlatformIO with the ‘official’ programmer on Windows, the baud rate at 9600 did not give any human readable results. Only when I set it on 115200 it gave some proper response. The guide explicitily states 9600, which was rather ‘frustrating’ for me, since I assumed something else than the baudrate was set wrong (you can imagine how many options one can try on platformIO serial monitor settings).

so and amendment would be much appreciated (by the future users!).

Thanks.

**Comment by glynhudson** [comment]
Thanks, been fixed
