### ISSUE TITLE
Index on Resources page makes little sense

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/guide#41]
The index on the 'Resources' page makes no sense as it is basically the index for the guide.

https://github.com/openenergymonitor/guide/blob/master/source/technical/resources.markdown

Could the text be compressed as there is far to much whitespace which results in excessive scrolling.

**Comment by SlyRemarks** [comment]
The problem is that 'Resources' page is part of the Guide - a link to it was added to the navigation after it was created. 

As for compressing the text - how about using the something like the summary/details html tag that is used on the forum to display server information?

**Comment by borpin** [comment]
The thing is, if the resources page is part of the guide, why does both Resources and Guide have an entry along the top banner?

All I wanted to find was the Github link!

**Comment by SlyRemarks** [comment]
> All I wanted to find was the Github link!
A GitHub link to the Resources page, or to one of the HW or SW repos listed in Resources?

Originally, Resources wasn't on the top banner - it was added later. I think it was requested afterwards - so it ended up being this way. 

What do you think of collapsing each item listed in Resources?

**Comment by borpin** [comment]
Yes that will help.  Can the index on the right not be changed?

**Comment by SlyRemarks** [comment]
It can be. If the index is changed, it might be best to either remove Resources from the Guide (it's listed in the Guide index, a user on the Guide might get confused if the index disappears or changes if they browse to the Resources page from another Guide page) or host it elsewhere. The latter would risk breaking links.
