### ISSUE TITLE
Change light blue font to improve accessibility

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/guide#44]
In the same vein as #43, could the blue font be darker/heavier as well please?

e.g.

![image](https://user-images.githubusercontent.com/1322749/53258347-52abee00-36c4-11e9-9534-934231bbb8da.png)

**Comment by SlyRemarks** [comment]
Fixed by https://github.com/openenergymonitor/guide/commit/92785e350984ea6bafc87e54f7137815dd556db0
